In [1]:
import pandas as pd
import numpy as np

def calculate_rsi(data, window=14):
    """
    计算相对强弱指数（RSI）。
    
    :param data: 包含收盘价的Pandas DataFrame，列名为'close'
    :param window: RSI计算的时间窗口，默认为14
    :return: 返回计算得到的RSI值
    """
    # 计算收盘价的日变化
    delta = data['close'].diff()
    
    # 将正负变化分开
    gain = delta.where(delta > 0, 0)
    loss = -delta.where(delta < 0, 0)
    
    # 计算平均增益和平均损失
    avg_gain = gain.rolling(window=window).mean()
    avg_loss = loss.rolling(window=window).mean()
    
    # 计算相对强度（RS）
    rs = avg_gain / avg_loss
    
    # 计算RSI
    rsi = 100 - (100 / (1 + rs))
    
    return rsi

# 示例数据
data = pd.read_csv('23_11_24_8.csv')

# bulinge upper band
data['SMA'] = data['close'].rolling(window=20).mean()
# 计算标准差（Standard Deviation）
data['SD'] = data['close'].rolling(window=20).std()
# 计算布林格上界（Upper Band）
data['Upper_band'] = data['SMA'] + 2 * data['SD']
data['Lower_Band'] = data['SMA'] - 2 * data['SD']
#rsi
data['RSI'] = calculate_rsi(data)
#m12
data['M12'] = data['close'].pct_change(periods=12)
#计算ATR
data['High-Low'] = data['high'] - data['low']
data['High-Close Prev'] = (data['high'] - data['close'].shift()).abs()
data['Low-Close Prev'] = (data['low'] - data['close'].shift()).abs()
data['True Range'] = data[['High-Low', 'High-Close Prev', 'Low-Close Prev']].max(axis=1)
data['ATR'] = data['True Range'].rolling(window=14).mean()

# 输出结果
print(data[['date', 'close', 'RSI','M12','Upper_band','Lower_Band','SMA','SD','ATR']])

           date    close        RSI       M12   Upper_band   Lower_Band  \
0    2023-11-01  3571.03        NaN       NaN          NaN          NaN
1    2023-11-02  3554.19        NaN       NaN          NaN          NaN
2    2023-11-03  3584.14        NaN       NaN          NaN          NaN
3    2023-11-06  3632.61        NaN       NaN          NaN          NaN
4    2023-11-07  3619.76        NaN       NaN          NaN          NaN
..          ...      ...        ...       ...          ...          ...
200  2024-08-26  3324.22  44.219867 -0.005600  3414.850628  3280.190372
201  2024-08-27  3305.33  39.937667 -0.007894  3413.341984  3275.294016
202  2024-08-28  3286.50  35.679488 -0.011835  3393.118204  3279.959796
203  2024-08-29  3277.68  36.136095 -0.017008  3377.194089  3281.724911
204  2024-08-30  3321.43  49.047517  0.003684  3366.501109  3286.121891

           SMA         SD        ATR
0          NaN        NaN        NaN
1          NaN        NaN        NaN
2          NaN        NaN        NaN
3          NaN        NaN        NaN
4          NaN        NaN        NaN
..         ...        ...        ...
200  3347.5205  33.665064  31.584286
201  3344.3180  34.511992  31.030714
202  3336.5390  28.289602  30.088571
203  3329.4595  23.867295  29.104286
204  3326.3115  20.094805  33.375000

[205 rows x 9 columns]

In [2]:
data

,date,close,open,high,low,flucamount,amplitude,turnoverrate,RV_5min,rv_w,...,SD,Upper_band,Lower_Band,RSI,M12,High-Low,High-Close Prev,Low-Close Prev,True Range,ATR
0,2023-11-01,3571.03,3605.76,3606.41,3564.64,-1.48,1.17,0.3191,0.002717,NaN,...,NaN,NaN,NaN,NaN,NaN,41.77,NaN,NaN,41.77,NaN
1,2023-11-02,3554.19,3580.07,3597.17,3553.74,-16.84,1.22,0.2953,0.002918,NaN,...,NaN,NaN,NaN,NaN,NaN,43.43,26.14,17.29,43.43,NaN
2,2023-11-03,3584.14,3558.53,3596.10,3558.53,29.95,1.06,0.3188,0.003910,NaN,...,NaN,NaN,NaN,NaN,NaN,37.57,41.91,4.34,41.91,NaN
3,2023-11-06,3632.61,3608.32,3635.79,3600.63,48.47,0.98,0.5000,0.004483,NaN,...,NaN,NaN,NaN,NaN,NaN,35.16,51.65,16.49,51.65,NaN
4,2023-11-07,3619.76,3623.78,3628.46,3606.30,-12.85,0.61,0.3604,0.002158,0.003237,...,NaN,NaN,NaN,NaN,NaN,22.16,4.15,26.31,26.31,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,2024-08-26,3324.22,3330.72,3336.53,3311.57,-2.97,0.75,0.2995,0.002916,0.003934,...,33.665064,3414.850628,3280.190372,44.219867,-0.005600,24.96,9.34,15.62,24.96,31.584286
201,2024-08-27,3305.33,3315.69,3320.57,3299.56,-18.89,0.63,0.3052,0.002087,0.003729,...,34.511992,3413.341984,3275.294016,39.937667,-0.007894,21.01,3.65,24.66,24.66,31.030714
202,2024-08-28,3286.50,3298.91,3305.35,3274.59,-18.84,0.93,0.2953,0.004355,0.003778,...,28.289602,3393.118204,3279.959796,35.679488,-0.011835,30.76,0.02,30.74,30.76,30.088571
203,2024-08-29,3277.68,3273.54,3290.79,3269.53,-8.81,0.65,0.4164,0.003674,0.003622,...,23.867295,3377.194089,3281.724911,36.136095,-0.017008,21.26,4.29,16.97,21.26,29.104286
204,2024-08-30,3321.43,3273.75,3351.63,3273.65,43.75,2.38,0.6012,0.007426,0.004092,...,20.094805,3366.501109,3286.121891,49.047517,0.003684,77.98,73.95,4.03,77.98,33.375000

In [3]:
data.to_csv('23_24.csv')